#!/bin/bash
########################################################################
# Copyright (C) 2021		Alejandro Colomar <alx.manpages@gmail.com>
# SPDX-License-Identifier:	GPL-2.0-only OR LGPL-2.0-only
########################################################################


_d="$(dirname "${BASH_SOURCE[0]}")";
_D="${_d}/..";

nginx_dep="${_D}/etc/docker/dependencies/nginx";

arch="x86_64";

nginx_reg="$(<${nginx_dep} grep '^reg' | cut -f2)";
nginx_user="$(<${nginx_dep} grep '^user' | cut -f2)";
nginx_repo="$(<${nginx_dep} grep '^repo' | cut -f2)";
nginx_lbl="$(<${nginx_dep} grep '^lbl' | cut -f2)";
nginx_digest="$(<${nginx_dep} grep '^digest' | grep "${arch}" | cut -f3)";

sed -i \
	-e "/^ARG	NGINX_REG=/s/=.*/=${nginx_reg}/" \
	-e "/^ARG	NGINX_USER=/s/=.*/=${nginx_user}/" \
	-e "/^ARG	NGINX_REPO=/s/=.*/=${nginx_repo}/" \
	-e "/^ARG	NGINX_LBL=/s/=.*/=${nginx_lbl}/" \
	-e "/^ARG	NGINX_DIGEST=/s/=.*/=${nginx_digest}/" \
	${_D}/Dockerfile;
